### ISSUE TITLE
PHP Fatal error:  Call to undefined method Doctrine\ORM\Internal\CommitOrderCalculator::addClass() in .../Doctrine/Common/DataFixtures/Purger/ORMPurger.php on line 151

### ISSUE THREAD

**Issue by madebydavid** [doctrine/data-fixtures#213] opened 2015-12-02 22:18 UTC
I'm using silex with [useallfive/doctrine-data-fixtures-command](https://github.com/UseAllFive/doctrine-data-fixtures-command). Versions are `dev-master` of this repo and `dev-master` of doctrine2

The following error is raised when attempting to load fixtures:
```
PHP Fatal error:  Call to undefined method Doctrine\ORM\Internal\CommitOrderCalculator::addClass() in /var/www/html/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php on line 151
```
The `addClass` method seems to have been removed in [this commit](https://github.com/doctrine/doctrine2/commit/8ea62b95b8e4a8b3de000a59f018ec250b41d714)

**Comment by dkorsak** [comment] 2015-12-03 11:10
+1

**Comment by adampiotrowski** [comment] 2015-12-05 01:12
+1

**Comment by Ocramius** [comment] 2015-12-05 02:22
Duplicate of #212

**Closed by Ocramius** 2015-12-05 02:22 UTC
