### ISSUE TITLE
Can't install with symfony 4.1

### ISSUE THREAD

**Issue by ehibes** [doctrine/data-fixtures#330] opened 2019-12-04 10:50 UTC
It seems to be a BC break installing this bundle with symfony 4.1.
If I specify to install version 3.0.2, it works.

**Comment by Ocramius** [comment] 2019-12-04 10:54
Van you provide more details, please?

**Comment by ehibes** [comment] 2019-12-04 11:22
Of course yes. First I installed symfony on version 4.1.
```
composer create-project symfony/website-skeleton my_project_name 4.1.*
```
After, I tried to install orm-fixtures : 
```
composer require --dev orm-fixtures
```
I get this error from composer 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/doctrine-fixtures-bundle ^3.3 -> satisfiable by doctrine/doctrine-fixtures-bundle[3.3.0].
    - doctrine/doctrine-fixtures-bundle 3.3.0 requires symfony/config ^3.4|^4.3|^5.0 -> no matching package found.
```
If I specify orm fixtures version, no problem. Is it a normal behavior or composer have to find the right version ?
```
composer require --dev orm-fixtures 3.0.2
```

**Comment by Ocramius** [comment] 2019-12-04 11:32
not sure what the `orm-fixtures` package is: seems like a flex issue on that end.

What's `composer require --dev doctrine/data-fixtures`?

**Comment by ehibes** [comment] 2019-12-04 11:40
It’s ok with this command

**Comment by Ocramius** [comment] 2019-12-04 12:02
Closing here then: the problem is downstream, in the `orm-fixture` recipe (not sure where/who maintains that, sorry)

**Closed by Ocramius** 2019-12-04 12:02 UTC

**Comment by stof** [comment] 2019-12-04 13:29
Well, if you require `doctrine/data-fixtures`, you're not getting the same requirement than what the Flex alias `orm-fixture` gives you. The equivalent would be `composer require --dev doctrine/data-fixtures-bundle`.

And you can install the bundle with Symfony 4.1 if you specify a version constraint allowing older release. When you don't specify a constraint yourselves, composer automatically generates one as `^latest` (replacing `latest` with the latest stable release). And the latest release version of the DataFixturesBundle is indeed not compatible with EOLed Symfony versions.

**Comment by btinet** [comment] 2020-08-26 15:58
I've got the same problem now. Tested on two machines.

Some weeks ago, it worked perfectly.

**Comment by btinet** [comment] 2020-08-26 17:11
Just paste under require-dev in composer.json and update:

"doctrine/doctrine-fixtures-bundle": "^3.3",
