### ISSUE TITLE
Add new tag

### ISSUE THREAD

**Issue by TomasVotruba** [doctrine/data-fixtures#161] opened 2014-09-04 16:07 UTC
I'd like to use this package as dependency with up-to-date commits in my extension.

**Comment by jewome62** [comment] 2015-01-15 14:21
+1

**Comment by lavoiesl** [comment] 2015-03-22 20:04
Duplicate of #158

**Closed** 2015-03-22 20:05 UTC
Labels: Duplicate, Question

**Comment by TomasVotruba** [comment] 2015-03-22 20:11
Thanks @lavoiesl , I haven't noticed
