### ISSUE TITLE
Attempted to call an undefined method named "addClass" of class "Doctrine\O RM\Internal\CommitOrderCalculator

### ISSUE THREAD

**Issue by Wobbly-Wibbly** [doctrine/data-fixtures#217] opened 2016-01-24 12:08 UTC
I have just installed a fresh instance of Symfony2.
```
composer require --dev doctrine/doctrine-fixtures-bundle
```
and when I run 
```
php app/console doctrine:fixtures:load
```

I get this error 
```
Attempted to call an undefined method named "addClass" of class "Doctrine\O RM\Internal\CommitOrderCalculator
```

I looked into the code and addClass is called on CommitOrderCalculator.
https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php#L151

But I have checked Doctrine repository and they don't have such method.
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Internal/CommitOrderCalculator.php

**Comment by Ocramius** [comment] 2016-01-24 14:33
Duplicate of #212

**Closed by Ocramius** 2016-01-24 14:33 UTC
