### ISSUE TITLE
TopologicalSorter breaks fixture load

### ISSUE THREAD

**Issue by peterrehm** [doctrine/data-fixtures#228] opened 2016-06-20 08:31 UTC
The TopologicalSorter throws the error:

````
 Graph contains cyclic dependency. An example of this problem would be the following: Class C has class B as its dependency. Then, class B has class A has its dependency. Finally, class A has class C as its dependency. 
````

Everything was working before. As the error is not providing much information I will investigate further.

**Comment by peterrehm** [comment] 2016-06-20 08:41
It looks like this might be due to a self referencing entity.

**Comment by magnetik** [comment] 2016-06-20 08:44
Indeed it happens for me on a self referencing ManyToOne in my case.

**Comment by peterrehm** [comment] 2016-06-20 08:50
Just provided a PR, let's see if this is the solution already.

**Comment by AxaliaN** [comment] 2016-06-20 09:48
I hope it gets merged soon, same issue on our end.

**Comment by Xen3r0** [comment] 2016-06-20 10:17
I have the same problem, can't start my fixtures :(

Anyone have a solution ?

**Comment by AxaliaN** [comment] 2016-06-20 10:18
@Xen3r0 Use version 1.1.1 for now, it's what I did.

**Comment by kniziol** [comment] 2016-06-20 10:38
Same problem here. **Cannot load DataFixtures with entities that reference them self**. Removing those entities solves the problem, but it's not a good solution, because many data is not loaded while recreating database... I have a _Category_ entity who **implements tree functionality based on _@Gedmo\TreeParent_**. So, the _Category_ contains reference to itself and... that's the problem.

Using version 1.1.1 solves the problem too, but it's temporarily solution.

**Comment by cfuerst** [comment] 2016-06-20 11:28
Same issue here with Gedmo\Tree 👍

**Comment by peterrehm** [comment] 2016-06-20 11:36
Can you try if my fix resolves it for your use cases?

**Comment by Ocramius** [comment] 2016-06-20 11:38
Please, folks, come up with test cases and sample scenarios that we can put in the test suite. We know that the new `TopologicalSorter` is not 100% reflecting what was in ORM 2.5, but we can't do much about it without actual tests that cover the solved problems.

**Comment by geoffrey-brier** [comment] 2016-06-20 14:45
@Ocramius In my case the fixtures load correctly but if I reload them, the DELETE FROM <table> breaks everything (after upgrading from 1.1 to 1.2). I could provide the schema and alice fixtures but it's quite big.

**Closed** 2016-06-20 18:08 UTC
Labels: Bug, Needs tests

**Comment by peterrehm** [comment] 2016-06-20 18:46
@geoffrey-brier Your issue might not be solved with the merged PR. Please check this again and open an issue if it still exists.

**Comment by mikemix** [comment] 2016-10-11 14:05
Using version 1.2.1 the issue is still there with this set up:

```php
/**
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discriminator", type="string")
 * @ORM\DiscriminatorMap({
 *     "super1" = "AppBundle\Entity\Super1",
 *     "super2" = "AppBundle\Entity\Super2"
 * })
 * @ORM\Table
 */
abstract class Super
{
    /**
     * var self
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Super", inversedBy="revisions")
     * @ORM\JoinColumn(name="parent_id", nullable=true)
     */
    private $parent;

    /**
     * @var self[]
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Super", mappedBy="parent")
     */
    private $revisions;
}
```

Error when trying to load the fixtures:

```php
[Doctrine\Common\DataFixtures\Exception\CircularReferenceException]                                                                                                                                                       
  Graph contains cyclic dependency. An example of this problem would be the following: Class C has class B as its dependency. Then, class B has class A has its dependency. Finally, class A has class C as its dependency
```

The schema mapping is ok, the relation is working too.
